import re
phoneNumRegex = re.compile(r'(\(\d\d\d\)) (\d\d\d-\d\d\d\d)')
mo = phoneNumRegex.search('My number is (415) 555-4242.')
print(mo.group(1))
print(mo.group(2))
phoneNumRegex = re.compile(r'(\(\d\d\d\))-(\d\d\d-\d\d\d\d)')
mo1 = phoneNumRegex.search('My number is (415)-555-4242.')
print (mo1.group())
#phoneNumRegex = re.compile(r'(\d\d\d\) (\d\d\d)-(\d\d\d\d)')
#mo2 = phoneNumRegex.search('My number is 415 555-4242.')
#print (mo2.group())
#phoneNumRegex = re.compile(r'(\d\d\d\)-(\d\d\d)-(\d\d\d\d)')
phoneNumRegex = re.compile(r'\d\d\d-\d\d\d-\d\d\d\d')
mo3 = phoneNumRegex.search("My number is 415-555-4242.")
print (mo3.group())
