import numpy as np
# np.zeros
print("create numpy with all ZERO's")
n1 = np.zeros((5,5))
print(n1)
print("\ncreate a numpy with same number")
n2 = np.full((3,3),10)
print (n2)
print ("\ninitializing Numpy within a range")
n3 = np.arange(10,20)
print(n3)
n4 = np.arange(10,50,5)
print(n4)
print ("\nInitializing NumPy with random numbers. telling how many random numbers we need\nIn our case it is just 5")
n5=np.random.randint(1,100,5)
print (n5)
print("\nCheck the shape of numpy array, rows & Column")
n6 = np.full((5,2),8)
print(n6)
print(n6.shape)
print ("\nNow I want to change the shape from (5,2 to (2,5)")
n6.shape = (2,5)
print(n6.shape)
print (n6)